# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.4.5-cli

    steps:
      - checkout

      - run: sudo apt update
      - run: sudo docker-php-ext-install bcmath
      - run: composer install -n --prefer-dist
      - run: ./vendor/bin/phpunit ./test/Unit
      - run: ./vendor/bin/phpcs --colors --report-width=200 --standard=PSR12 --exclude=PSR12.Files.FileHeader,Generic.Files.LineLength ./src
